const PATHS = {
    MAIN: '/',
    LOGIN: '/member/login',
    MY_PAGE: '/my-page/index',
    MY_INFO: '/my-page/info',
    MY_ORDER_LIST: '/my-page/order/list',
    MY_ORDER_DETAIL: '/my-page/order/detail',
    MY_PRODUCTS: '/my-page/products',
    MY_COUPONS: '/my-page/coupons',
    MY_ACCUMULATION: '/my-page/accumulation',
    CART: '/cart',
    SEARCH: '/search',
    EVENT_LIST: '/event/list',
    EVENT_DETAIL: '/event/detail',
    GUEST_LOGIN: '/guest/login',
    GUEST_ORDER: '/guest/order',
    GUEST_ORDER_DETAIL: '/guest/order/detail',
    MANAGER: '/manager',
    MANUAL_LIST: '/manual/list',
    MANUAL_DETAIL: '/manual/detail',
    GOLF_COURSE_LIST: '/golf-course/list',
    GOLF_COURSE_DETAIL: '/golf-course/detail',
    GOLF_COURSE_REQUEST: '/golf-course/request',
    FAQ: '/etc/faq',
    NOTICE: '/etc/notice',
    NOT_FOUND: '/not-found',
    ERROR: '/error-server',
};

export default PATHS;
