const PAY_TYPES = {
    CREDIT_CARD: '신용카드',
    ACCOUNT: '무통장입금',
    MOBILE: '휴대폰결제',
    REALTIME_ACCOUNT_TRANSFER: '실시간계좌이체',
    VIRTUAL_ACCOUNT: '가상계좌',
    GIFT: '상품권',
    ATM: 'ATM',
    PAYCO: 'PAYCO',
    ZERO_PAY: '0원결제',
    ACCUMULATION: '적립금 전액 사용',
    PHONE_BILL: '전화결제',
    POINT: '포인트결제',
    YPAY: '옐로페이',
    KPAY: '케이페이',
    PAYPIN: '페이핀',
    INIPAY: 'INIPay 간편결제',
    PAYPAL: 'PAYPAL',
    STRIPE: 'STRIPE',
    NAVER_PAY: '네이버페이 주문형',
    KAKAO_PAY: '카카오페이',
    NAVER_EASY_PAY: '네이버페이 결제형',
    SAMSUNG_PAY: '삼성페이',
    CHAI: '차이',
    TOSS_PAY: '토스페이',
    ESCROW_REALTIME_ACCOUNT_TRANSFER: '실시간계좌이체-에스크로',
    ESCROW_VIRTUAL_ACCOUNT: '가상계좌-에스크로',
    RENTAL: '렌탈결제',
    VERITRANS_CARD: 'Veritrans CreditCard',
    TOASTCAM: '토스트캠',
    ETC: '기타결제수단',
};

export default PAY_TYPES;
